### ISSUE TITLE
Update inputs

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/gaia2_kep_rot#2]
- [x] get updated match (1 arcsecond) from @megbedell
- [x] use [bailer-jones2018](https://arxiv.org/abs/1804.10121) distances
- [x] use new isochrones? e.g. change metallicity? The default Padova isochrone doesn't fit CMD very well... @kevincovey maybe has thoughts here?
- [x] use different gyrochronology prescription? The [Meibom+2009](http://adsabs.harvard.edu/abs/2009ApJ...695..679M) doesn't look great...

**Comment by kevincovey** [comment]
- [ ] construct Toomre diagram (or just proper motion diagram) for top and bottom of main sequence to test if kinematics are getting hotter with the vertical shift.  If the stars that are higher up in the band are older, the proper motions should be larger from Galactic heating...

**Comment by jradavenport** [comment]
Looks like I need to read this tutorial:
http://docs.astropy.org/en/stable/generated/examples/coordinates/plot_galactocentric-frame.html

**Comment by megbedell** [comment]
There's a snippet of code around cells 58-60 [here](https://github.com/megbedell/gaia-kepler.fun/blob/master/notebooks/demo.ipynb) that might help with the coordinate transformation - one thing I learned the hard way is that astropy.coordinates does NOT like NaN RVs or negative parallaxes, so those objects should be masked out and/or RV set to zero before making the SkyCoord objects.

(sorry I'm creepin on your issue)

**Comment by jradavenport** [comment]
Awesome, thank you @megbedell!

**Comment by jradavenport** [comment]
Stuck w/ the Meibom'09 model, but just used MIST model to convert colors to B-V
